Update BeginningTraining.md 2023
chopshop-166/SoftwareTraining pull request #5
Opened 2023-08-26 16:47 UTC by TimnJoey

Moved some things around in the first three weeks, added "Projects" section for the weeks that have projects, changed meeting to week, added 4 extra weeks.

2023-09-08 01:11 UTC, msoucy commented on Training Plan/BeginningTraining.md
> +((( (- [ ] Averaging Robot exercise
Punctuation attack!

2023-09-08 01:11 UTC, msoucy commented on Training Plan/BeginningTraining.md
> +For when the going gets tough and there isn't enough material to fill the tim
Please don't fill the tim

2023-09-12 22:47 UTC, bot190 requested changes
It looks like you've stretched the training schedule out but not added more content, how do we plan to spend the extra time?

2023-09-12 22:47 UTC, bot190 commented on Training Plan/BeginningTraining.md
> +  - Basic subsystem with mock motors and sensors
More detail here? Matt and I can help fill in details if you can add more direction.

2024-08-23 00:42 UTC, closed without merging